export const paths = {
  home: "/",
  business: "/business",
  login: "/login",
  register: "/register",
  businessForm: "/businessForm",
  detail: "/detail",
  search: "/search",
  forget_password: "/forget_password",
  search_business: "/search_business/:id",
  search_city: "/search_city/:id",
  business_information: "/business_information",
  business_deatil: "/business_card_detail/:id",
  profile: "/profile",
  business_edit: "/edit",,
  faceook_login:"/auth/facebook/callback",
};
